#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ToDo.Resource", IsApplication=true)]

namespace ToDo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ToDoLibrary.Resource.String.library_name = global::ToDo.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int date32 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int delete32 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int edit = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int exit = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int green = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int grey = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int monoandroidsplash = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int orange = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int red = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tick26black = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int time32 = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070017
			public const int CreateToDoButton = 2131165207;
			
			// aapt resource value: 0x7f070011
			public const int DateButton = 2131165201;
			
			// aapt resource value: 0x7f070007
			public const int IndicatorImage = 2131165191;
			
			// aapt resource value: 0x7f070018
			public const int MarkCompleted = 2131165208;
			
			// aapt resource value: 0x7f070005
			public const int SignUpButton = 2131165189;
			
			// aapt resource value: 0x7f070014
			public const int TimeButton = 2131165204;
			
			// aapt resource value: 0x7f07000e
			public const int ToDoDescEditText = 2131165198;
			
			// aapt resource value: 0x7f070012
			public const int ToDoDureDateTextView = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int ToDoDureTimeTextView = 2131165205;
			
			// aapt resource value: 0x7f070019
			public const int ToDoExpandableListView = 2131165209;
			
			// aapt resource value: 0x7f070006
			public const int ToDoListHeader = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int ToDoTitleEditText = 2131165195;
			
			// aapt resource value: 0x7f07001a
			public const int action_add = 2131165210;
			
			// aapt resource value: 0x7f070016
			public const int linearLayout1 = 2131165206;
			
			// aapt resource value: 0x7f070004
			public const int loginButton = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int passwordText = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int tableLayout1 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int tableRow1 = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int tableRow2 = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int tableRow3 = 2131165199;
			
			// aapt resource value: 0x7f070013
			public const int tableRow4 = 2131165203;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int textView10 = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int textView11 = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int textView12 = 2131165200;
			
			// aapt resource value: 0x7f070002
			public const int textView2 = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int usernameText = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ToDoExpandableListViewHeader = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ToDoLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ToDoMain = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int ToDoMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
