#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RestaurantActivity.Resource", IsApplication=true)]

namespace RestaurantActivity
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::RestaurantLibrary.Resource.String.library_name = global::RestaurantActivity.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int leftin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int leftout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int pushdownin = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int pushdownout = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int pushupin = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int pushupout = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int rightin = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int rightout = 2130968583;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int Persons = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int YesNo = 2131165185;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int bgclicked = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int bgnormal = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int RegisterLink = 2131099650;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int buttonBackground = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cart32 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int checklist_icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int CloseGrey = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int date32 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int foodItemBorder = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int foodItemBorderBack = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_drawer_toggle = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int monoandroidsplash = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int next = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int no_icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int time32 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int user1 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int user2 = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a001f
			public const int ACSpinner = 2131361823;
			
			// aapt resource value: 0x7f0a0052
			public const int ACTextView = 2131361874;
			
			// aapt resource value: 0x7f0a0049
			public const int AddressTextView = 2131361865;
			
			// aapt resource value: 0x7f0a0008
			public const int AmtDetailsAdvanceTextView = 2131361800;
			
			// aapt resource value: 0x7f0a0004
			public const int AmtDetailsItemsCostTextView = 2131361796;
			
			// aapt resource value: 0x7f0a000f
			public const int AmtDetailsTotalCostTextView = 2131361807;
			
			// aapt resource value: 0x7f0a000c
			public const int AmtDetailsVatTextView = 2131361804;
			
			// aapt resource value: 0x7f0a0065
			public const int BookDetailsACTextView = 2131361893;
			
			// aapt resource value: 0x7f0a0067
			public const int BookDetailsCostTextView = 2131361895;
			
			// aapt resource value: 0x7f0a005d
			public const int BookDetailsDateTextView = 2131361885;
			
			// aapt resource value: 0x7f0a0057
			public const int BookDetailsEmailTextView = 2131361879;
			
			// aapt resource value: 0x7f0a0062
			public const int BookDetailsPersonTextView = 2131361890;
			
			// aapt resource value: 0x7f0a005b
			public const int BookDetailsRestaurantTextView = 2131361883;
			
			// aapt resource value: 0x7f0a0060
			public const int BookDetailsTimeTextView = 2131361888;
			
			// aapt resource value: 0x7f0a0056
			public const int BookDetailsUsernameTextView = 2131361878;
			
			// aapt resource value: 0x7f0a0068
			public const int BookDetailsViewOrderDetailsButton = 2131361896;
			
			// aapt resource value: 0x7f0a0017
			public const int BookHoteNameTextView = 2131361815;
			
			// aapt resource value: 0x7f0a0026
			public const int BookSpinnerItemBookingIdTextView = 2131361830;
			
			// aapt resource value: 0x7f0a0025
			public const int BookSpinnerItemRestaurantNameTextView = 2131361829;
			
			// aapt resource value: 0x7f0a0028
			public const int BookSpinnerItemTotalDateTextView = 2131361832;
			
			// aapt resource value: 0x7f0a0018
			public const int BookedByTextView = 2131361816;
			
			// aapt resource value: 0x7f0a0012
			public const int BookedDetailsItemCostTextView = 2131361810;
			
			// aapt resource value: 0x7f0a0011
			public const int BookedDetailsItemNameTextView = 2131361809;
			
			// aapt resource value: 0x7f0a0014
			public const int BookedOrderDetailsItemCountTextView = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int BookedOrderDetailsListView = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int BookedOrderDetailsTotalCost = 2131361814;
			
			// aapt resource value: 0x7f0a0058
			public const int BookingDetailsSpinner = 2131361880;
			
			// aapt resource value: 0x7f0a0024
			public const int BookingProceedButton = 2131361828;
			
			// aapt resource value: 0x7f0a0036
			public const int BookingTotalCostTextView = 2131361846;
			
			// aapt resource value: 0x7f0a002e
			public const int CartFoodCostTextView = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public const int CartFoodCountTextView = 2131361839;
			
			// aapt resource value: 0x7f0a002a
			public const int CartFoodItemTextView = 2131361834;
			
			// aapt resource value: 0x7f0a002c
			public const int CartFoodTypeTextView = 2131361836;
			
			// aapt resource value: 0x7f0a0029
			public const int CartListView = 2131361833;
			
			// aapt resource value: 0x7f0a0037
			public const int ConfirmOrderButton = 2131361847;
			
			// aapt resource value: 0x7f0a001a
			public const int DateImageView = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int DateTextView = 2131361819;
			
			// aapt resource value: 0x7f0a003a
			public const int EmaiEditText = 2131361850;
			
			// aapt resource value: 0x7f0a0032
			public const int FoodItemCostTextView = 2131361842;
			
			// aapt resource value: 0x7f0a0033
			public const int FoodItemCountTextView = 2131361843;
			
			// aapt resource value: 0x7f0a0030
			public const int FoodItemImageView = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public const int FoodItemNameTextView = 2131361841;
			
			// aapt resource value: 0x7f0a0034
			public const int FoodItemTypeNameTextView = 2131361844;
			
			// aapt resource value: 0x7f0a0035
			public const int FoodItemsListView = 2131361845;
			
			// aapt resource value: 0x7f0a0050
			public const int FoodTypeTextView = 2131361872;
			
			// aapt resource value: 0x7f0a004e
			public const int LandmarkTextView = 2131361870;
			
			// aapt resource value: 0x7f0a0055
			public const int ListItemRestaurantNameTextView = 2131361877;
			
			// aapt resource value: 0x7f0a004a
			public const int LocationTextView = 2131361866;
			
			// aapt resource value: 0x7f0a003d
			public const int LoginButton = 2131361853;
			
			// aapt resource value: 0x7f0a003e
			public const int NewUserLinkText = 2131361854;
			
			// aapt resource value: 0x7f0a003c
			public const int PasswordEditText = 2131361852;
			
			// aapt resource value: 0x7f0a0019
			public const int PersonNoSpinner = 2131361817;
			
			// aapt resource value: 0x7f0a004c
			public const int PhoneTextView = 2131361868;
			
			// aapt resource value: 0x7f0a0045
			public const int RegisterButton = 2131361861;
			
			// aapt resource value: 0x7f0a0041
			public const int RegisterMailTextView = 2131361857;
			
			// aapt resource value: 0x7f0a0040
			public const int RegisterNameTextView = 2131361856;
			
			// aapt resource value: 0x7f0a0044
			public const int RegisterPasswordTextView = 2131361860;
			
			// aapt resource value: 0x7f0a0042
			public const int RegisterPhoneTextView = 2131361858;
			
			// aapt resource value: 0x7f0a0038
			public const int RestaurantNameListView = 2131361848;
			
			// aapt resource value: 0x7f0a0047
			public const int RestaurantNameTextView = 2131361863;
			
			// aapt resource value: 0x7f0a0023
			public const int SelectNoRadio = 2131361827;
			
			// aapt resource value: 0x7f0a0022
			public const int SelectYesRadio = 2131361826;
			
			// aapt resource value: 0x7f0a001c
			public const int TimeImageView = 2131361820;
			
			// aapt resource value: 0x7f0a0054
			public const int TimeServedTextView = 2131361876;
			
			// aapt resource value: 0x7f0a001d
			public const int TimeTextView = 2131361821;
			
			// aapt resource value: 0x7f0a0069
			public const int contextmenu_bookingdetails = 2131361897;
			
			// aapt resource value: 0x7f0a006b
			public const int contextmenu_myProfile = 2131361899;
			
			// aapt resource value: 0x7f0a006a
			public const int contextmenu_shoppingcart = 2131361898;
			
			// aapt resource value: 0x7f0a0046
			public const int imageView2 = 2131361862;
			
			// aapt resource value: 0x7f0a0010
			public const int linearLayout1 = 2131361808;
			
			// aapt resource value: 0x7f0a002b
			public const int linearLayout2 = 2131361835;
			
			// aapt resource value: 0x7f0a0021
			public const int radioGroup1 = 2131361825;
			
			// aapt resource value: 0x7f0a0000
			public const int tableLayout1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int tableRow1 = 2131361793;
			
			// aapt resource value: 0x7f0a0005
			public const int tableRow2 = 2131361797;
			
			// aapt resource value: 0x7f0a0009
			public const int tableRow3 = 2131361801;
			
			// aapt resource value: 0x7f0a000d
			public const int tableRow4 = 2131361805;
			
			// aapt resource value: 0x7f0a0013
			public const int textView1 = 2131361811;
			
			// aapt resource value: 0x7f0a0002
			public const int textView10 = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int textView11 = 2131361795;
			
			// aapt resource value: 0x7f0a000b
			public const int textView12 = 2131361803;
			
			// aapt resource value: 0x7f0a0007
			public const int textView13 = 2131361799;
			
			// aapt resource value: 0x7f0a000a
			public const int textView17 = 2131361802;
			
			// aapt resource value: 0x7f0a0006
			public const int textView18 = 2131361798;
			
			// aapt resource value: 0x7f0a002d
			public const int textView2 = 2131361837;
			
			// aapt resource value: 0x7f0a001e
			public const int textView20 = 2131361822;
			
			// aapt resource value: 0x7f0a0020
			public const int textView21 = 2131361824;
			
			// aapt resource value: 0x7f0a000e
			public const int textView22 = 2131361806;
			
			// aapt resource value: 0x7f0a0043
			public const int textView24 = 2131361859;
			
			// aapt resource value: 0x7f0a003f
			public const int textView26 = 2131361855;
			
			// aapt resource value: 0x7f0a0039
			public const int textView3 = 2131361849;
			
			// aapt resource value: 0x7f0a0059
			public const int textView35 = 2131361881;
			
			// aapt resource value: 0x7f0a005c
			public const int textView36 = 2131361884;
			
			// aapt resource value: 0x7f0a005e
			public const int textView37 = 2131361886;
			
			// aapt resource value: 0x7f0a0061
			public const int textView38 = 2131361889;
			
			// aapt resource value: 0x7f0a0063
			public const int textView39 = 2131361891;
			
			// aapt resource value: 0x7f0a003b
			public const int textView4 = 2131361851;
			
			// aapt resource value: 0x7f0a0066
			public const int textView40 = 2131361894;
			
			// aapt resource value: 0x7f0a0048
			public const int textView49 = 2131361864;
			
			// aapt resource value: 0x7f0a0027
			public const int textView5 = 2131361831;
			
			// aapt resource value: 0x7f0a004b
			public const int textView51 = 2131361867;
			
			// aapt resource value: 0x7f0a005a
			public const int textView52 = 2131361882;
			
			// aapt resource value: 0x7f0a004d
			public const int textView53 = 2131361869;
			
			// aapt resource value: 0x7f0a005f
			public const int textView54 = 2131361887;
			
			// aapt resource value: 0x7f0a004f
			public const int textView55 = 2131361871;
			
			// aapt resource value: 0x7f0a0064
			public const int textView56 = 2131361892;
			
			// aapt resource value: 0x7f0a0051
			public const int textView57 = 2131361873;
			
			// aapt resource value: 0x7f0a0053
			public const int textView60 = 2131361875;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AmountDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BookedOrderDetailsListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BookedOrderetails = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int BookingDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int BookingDetailsSpinnerItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CartDetails = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int CartListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FoodItemsListViewItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int FoodItemsParent = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Home = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Login = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Register = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int RestaurantDetails = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int RestaurantNameListViewItem = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int UserDetails = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int bookingDetailsMenu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int foodItemsParentMenu = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int userDetailsMenu = 2131296258;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int newUser = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Mono_Android_Theme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
