#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EventManager.Resource", IsApplication=true)]

namespace EventManager
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::EventLibrary.Resource.String.library_name = global::EventManager.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int date = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int delete = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int edit = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int exit = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int monoandroidsplash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int time = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070020
			public const int ConfAmtLabel = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int ConfAmtText = 2131165217;
			
			// aapt resource value: 0x7f070017
			public const int ConfHallNameLabel = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int ConfHallNameText = 2131165208;
			
			// aapt resource value: 0x7f07001d
			public const int ConfLandLabel = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int ConfLandText = 2131165214;
			
			// aapt resource value: 0x7f07001a
			public const int ConfOpeningHrsLabel = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int ConfOpeningHrsText = 2131165211;
			
			// aapt resource value: 0x7f070023
			public const int ConfPhoneLabel = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int ConfPhoneText = 2131165220;
			
			// aapt resource value: 0x7f07000a
			public const int DateImageButton = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int DateTableRow = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int DateTextView = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int EventNameTableRow = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int EventNameText = 2131165188;
			
			// aapt resource value: 0x7f070012
			public const int HallSpinner = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int HallTableRow = 2131165200;
			
			// aapt resource value: 0x7f070007
			public const int LocationSpinner = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int LocationTableRow = 2131165189;
			
			// aapt resource value: 0x7f070014
			public const int SaveEventButton = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int SaveTableRow = 2131165203;
			
			// aapt resource value: 0x7f07002a
			public const int SignUpButton = 2131165226;
			
			// aapt resource value: 0x7f07000e
			public const int TimeImageButton = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int TimeTableRow = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int TimeTextView = 2131165199;
			
			// aapt resource value: 0x7f07002b
			public const int action_add = 2131165227;
			
			// aapt resource value: 0x7f07002d
			public const int action_delete = 2131165229;
			
			// aapt resource value: 0x7f07002c
			public const int action_edit = 2131165228;
			
			// aapt resource value: 0x7f07002e
			public const int action_exit = 2131165230;
			
			// aapt resource value: 0x7f070001
			public const int drawerLayout = 2131165185;
			
			// aapt resource value: 0x7f070015
			public const int drawerListView = 2131165205;
			
			// aapt resource value: 0x7f070000
			public const int drawerText = 2131165184;
			
			// aapt resource value: 0x7f070029
			public const int loginButton = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int passwordText = 2131165224;
			
			// aapt resource value: 0x7f070002
			public const int tableLayout1 = 2131165186;
			
			// aapt resource value: 0x7f070016
			public const int tableRow1 = 2131165206;
			
			// aapt resource value: 0x7f070019
			public const int tableRow2 = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int tableRow3 = 2131165212;
			
			// aapt resource value: 0x7f07001f
			public const int tableRow4 = 2131165215;
			
			// aapt resource value: 0x7f070022
			public const int tableRow5 = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int textView1 = 2131165221;
			
			// aapt resource value: 0x7f070006
			public const int textView17 = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int textView18 = 2131165193;
			
			// aapt resource value: 0x7f070027
			public const int textView2 = 2131165223;
			
			// aapt resource value: 0x7f070011
			public const int textView21 = 2131165201;
			
			// aapt resource value: 0x7f07000d
			public const int textView28 = 2131165197;
			
			// aapt resource value: 0x7f070026
			public const int usernameText = 2131165222;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DrawerEventItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EventActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EventConfirmation = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int EventActivity = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int menu_main = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
