#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TripExpenseManager.Resource", IsApplication=true)]

namespace TripExpenseManager
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::TripExpenseLibrary.Resource.String.library_name = global::TripExpenseManager.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int date32 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int green32 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int grey32 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int monoandroidsplash = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int orange32 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int red32 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int tripnameHeader = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060022
			public const int AddExpenseButton = 2131099682;
			
			// aapt resource value: 0x7f06000c
			public const int AddTripButton = 2131099660;
			
			// aapt resource value: 0x7f060030
			public const int AllocatedTextView = 2131099696;
			
			// aapt resource value: 0x7f060006
			public const int ExpenseCostTextView = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int ExpenseNameTextView = 2131099651;
			
			// aapt resource value: 0x7f060029
			public const int FromDateTextView = 2131099689;
			
			// aapt resource value: 0x7f060028
			public const int FromTextView = 2131099688;
			
			// aapt resource value: 0x7f060025
			public const int HeaderTripNameTextView = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int HeaderTripStatusImageView = 2131099686;
			
			// aapt resource value: 0x7f060009
			public const int ListExpenseCostTextView = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int ListExpenseNameTextView = 2131099655;
			
			// aapt resource value: 0x7f06001d
			public const int SaveButton = 2131099677;
			
			// aapt resource value: 0x7f060031
			public const int SpentTextView = 2131099697;
			
			// aapt resource value: 0x7f06001c
			public const int TDAllocatedAmtTextView = 2131099676;
			
			// aapt resource value: 0x7f060017
			public const int TDFromDateImageControl = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int TDFromDateTextView = 2131099672;
			
			// aapt resource value: 0x7f060013
			public const int TDFromTextView = 2131099667;
			
			// aapt resource value: 0x7f060023
			public const int TDHeaderTextView = 2131099683;
			
			// aapt resource value: 0x7f060019
			public const int TDToDateImageControl = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int TDToDateTextView = 2131099674;
			
			// aapt resource value: 0x7f060015
			public const int TDToTextView = 2131099669;
			
			// aapt resource value: 0x7f060010
			public const int TDTripDescTextView = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int TDTripNameTextView = 2131099662;
			
			// aapt resource value: 0x7f06002d
			public const int ToDateTextView = 2131099693;
			
			// aapt resource value: 0x7f06002c
			public const int ToTextView = 2131099692;
			
			// aapt resource value: 0x7f06001e
			public const int TripDetailsExpanListView = 2131099678;
			
			// aapt resource value: 0x7f060021
			public const int TripExpenseBottomSpentTextView = 2131099681;
			
			// aapt resource value: 0x7f060024
			public const int TripExpenseHeaderStatusImageView = 2131099684;
			
			// aapt resource value: 0x7f06000b
			public const int TripOverviewListView = 2131099659;
			
			// aapt resource value: 0x7f06001f
			public const int linearLayout1 = 2131099679;
			
			// aapt resource value: 0x7f060000
			public const int tableLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060011
			public const int tableLayout2 = 2131099665;
			
			// aapt resource value: 0x7f060001
			public const int tableRow1 = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int tableRow2 = 2131099652;
			
			// aapt resource value: 0x7f060016
			public const int tableRow3 = 2131099670;
			
			// aapt resource value: 0x7f06000a
			public const int textView1 = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int textView10 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int textView11 = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int textView12 = 2131099661;
			
			// aapt resource value: 0x7f060027
			public const int textView13 = 2131099687;
			
			// aapt resource value: 0x7f06002a
			public const int textView16 = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int textView17 = 2131099691;
			
			// aapt resource value: 0x7f060008
			public const int textView2 = 2131099656;
			
			// aapt resource value: 0x7f06002e
			public const int textView20 = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int textView24 = 2131099695;
			
			// aapt resource value: 0x7f060020
			public const int textView3 = 2131099680;
			
			// aapt resource value: 0x7f06000f
			public const int textView41 = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int textView53 = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int textView54 = 2131099668;
			
			// aapt resource value: 0x7f06001b
			public const int textView59 = 2131099675;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ExpenseAlert = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ExpenseListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TripDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TripExpenseDetails = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TripExpenseDetailsHeader = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int tripListViewHeader = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int tripListViewListItem = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
